### ISSUE TITLE
깨지는 링크가 있습니다.

### ISSUE THREAD

**Issue by CoderK** [leehosung/awesome-devteam#10]
다음의 항목은 링크가 깨지네요.
사이트가 없어진 거 같습니다.

> [채용] 프론트+백엔드+데이타 개발자 - 모범적인 개발자 구인글
> 짝 프로그래밍에 관한 효과적인 지침서

직접 수정해도 될지 알 수 없어서 우선 이슈만 보고합니다 :)

**Comment by leehosung** [comment]
늦게 확인해서 죄송합니다. 제가 수정해도 됩니다만 PR을 주시면 더 좋겠습니다~
