### ISSUE TITLE
토스팀의 조직구조-content-link-issue

### ISSUE THREAD

**Issue by shinel94** [leehosung/awesome-devteam#34]
Readme.md
> 조직
>> [토스팀의 조직구조](http://tossthink.tistory.com/182)

상기 링크가 잘못되어 있는것 같습니다.

**Comment by leehosung** [comment]
제가 당시 읽었었던 글을 다시 찾을 수는 없네요. 관련 링크 정리해 두겠습니다. 

알려 주셔서 감사해요!
